####################################
# make the ChangeLog from git's history
ChangeLog: stamp-h1
	@if test -d "$(top_srcdir)/.git" ; \
	then \
		echo Creating ChangeLog && \
		( cd "$(top_srcdir)" && \
		  echo '# Generated by Makefile. Do not edit.'; echo; \
		  ./build-aux/missing --run git log --pretty=oneline ) > $(top_builddir)/ChangeLog.tmp \
		&& mv -f $(top_builddir)/ChangeLog.tmp $(top_builddir)/ChangeLog \
		|| ( rm -f $(top_builddir)/ChangeLog.tmp ; \
		     echo Failed to generate ChangeLog >&2 ); \
	else \
		echo A git clone is required to generate a ChangeLog >&2; \
		echo "empty" > $(top_builddir)/ChangeLog ; \
	fi
